name: parlo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  flutter_native_splash: ^2.4.5
  flutter_svg: ^2.0.9
  get_it: ^8.0.3
  flutter_easylogger: ^2.3.3
  flutter_secure_storage: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
  mocktail: ^1.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-Italic.ttf
          style: italic
  assets:
    - assets/icons/mail.svg
    - assets/icons/lock.svg
    - assets/icons/settings.svg
    - assets/icons/user.svg
    - assets/icons/user_white.svg
    - assets/icons/google.svg

flutter_native_splash:
  color: "#20242D"
  image: assets/logos/smooth_parrot.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: assets/logos/smooth_parrot.png
    color: "#20242D"
