name: parlo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  flutter_native_splash: ^2.4.5
  firebase_core: ^3.12.1
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-Italic.ttf
          style: italic
  assets:
    - .env
    - assets/icons/mail.svg
    - assets/icons/lock.svg
    - assets/icons/settings.svg
    - assets/icons/user.svg
    - assets/icons/user_white.svg
    - assets/icons/google.svg
    - assets/logos/smooth_parrot.png
    - assets/logos/parrot.png
    - assets/logos/full_parrot.png
    - assets/logos/colorful_parrot.png

flutter_native_splash:
  color: "#20242D"
  image: assets/logos/smooth_parrot.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: assets/logos/smooth_parrot.png
    color: "#20242D"
