// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALTjur6dgyHM_6Nk4yDThhFFtTDaubjcM',
    appId: '1:579507711414:android:39ae3807b32ea4ae992517',
    messagingSenderId: '579507711414',
    projectId: 'parlo-569c5',
    databaseURL:
        'https://parlo-569c5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parlo-569c5.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOTiovBl4Uc1EgSBj6akmAjHnHuWF4sbI',
    appId: '1:579507711414:ios:b4c0214d5bb90f5c992517',
    messagingSenderId: '579507711414',
    projectId: 'parlo-569c5',
    databaseURL:
        'https://parlo-569c5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parlo-569c5.firebasestorage.app',
    iosClientId:
        '579507711414-p81m418krj1818m22v303sfl2frtj3qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.parlo',
  );
}
